name: recruitment_assignment
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # http
  http: ^0.13.5

  # svg
  flutter_svg: ^1.0.3

  # Riverpod
  state_notifier: ^0.7.2+1
  flutter_hooks: ^0.18.3
  hooks_riverpod: ^1.0.3+1

  # Freezed
  freezed: ^2.0.4
  build_runner: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/icon/add.svg
    - asset/icon/cancel.svg
    - asset/icon/delete.svg
    - asset/icon/done.svg
    - asset/icon/edit.svg
    - asset/icon/logo.svg
    - asset/icon/save.svg